### 3D array creation
In the first lesson, you created a sudoku_game two-dimensional NumPy array. Perhaps you have hundreds of sudoku game arrays, and you'd like to save the solution for this one, sudoku_solution, as part of the same array as its corresponding game in order to organize your sudoku data better. You could accomplish this by stacking the two 2D arrays on top of each other to create a 3D array.

In [1]:
#Libraries
import numpy as np  #import NumPy
import matplotlib.pyplot as plt #import matplolib

In [6]:
sudoku_game_l=[[0, 0, 4, 3, 0, 0, 2, 0, 9],
       [0, 0, 5, 0, 0, 9, 0, 0, 1],
       [0, 7, 0, 0, 6, 0, 0, 4, 3],
       [0, 0, 6, 0, 0, 2, 0, 8, 7],
       [1, 9, 0, 0, 0, 7, 4, 0, 0],
       [0, 5, 0, 0, 8, 3, 0, 0, 0],
       [6, 0, 0, 0, 0, 0, 1, 0, 5],
       [0, 0, 3, 5, 0, 8, 6, 9, 0],
       [0, 4, 2, 9, 1, 0, 3, 0, 0]]

# Convert sudoku_game_l into an array
sudoku_game = np.array(sudoku_game_l)

# Print the type of sudoku_array 
print(type(sudoku_game))
np.ndim(sudoku_game_l)

<class 'numpy.ndarray'>


2

In [7]:
sudoku_solution_l=[[8, 6, 4, 3, 7, 1, 2, 5, 9],
       [3, 2, 5, 8, 4, 9, 7, 6, 1],
       [9, 7, 1, 2, 6, 5, 8, 4, 3],
       [4, 3, 6, 1, 9, 2, 5, 8, 7],
       [1, 9, 8, 6, 5, 7, 4, 3, 2],
       [2, 5, 7, 4, 8, 3, 9, 1, 6],
       [6, 8, 9, 7, 3, 4, 1, 2, 5],
       [7, 1, 3, 5, 2, 8, 6, 9, 4],
       [5, 4, 2, 9, 1, 6, 3, 7, 8]]

# Convert sudoku_game_l into an array
sudoku_solution = np.array(sudoku_solution_l)

# Print the type of sudoku_array 
print(type(sudoku_solution))
np.ndim(sudoku_solution)

<class 'numpy.ndarray'>


2

In [5]:
#Create a 3D array called game_and_solution by stacking the two 2D arrays, sudoku_game and sudoku_solution, on top of one another; in the final array, sudoku_game should appear before sudoku_solution.
game_and_solution = np.array([sudoku_game,sudoku_solution])
#Print game_and_solution
print(game_and_solution) 
np.ndim(game_and_solution)

[[[0 0 4 3 0 0 2 0 9]
  [0 0 5 0 0 9 0 0 1]
  [0 7 0 0 6 0 0 4 3]
  [0 0 6 0 0 2 0 8 7]
  [1 9 0 0 0 7 4 0 0]
  [0 5 0 0 8 3 0 0 0]
  [6 0 0 0 0 0 1 0 5]
  [0 0 3 5 0 8 6 9 0]
  [0 4 2 9 1 0 3 0 0]]

 [[8 6 4 3 7 1 2 5 9]
  [3 2 5 8 4 9 7 6 1]
  [9 7 1 2 6 5 8 4 3]
  [4 3 6 1 9 2 5 8 7]
  [1 9 8 6 5 7 4 3 2]
  [2 5 7 4 8 3 9 1 6]
  [6 8 9 7 3 4 1 2 5]
  [7 1 3 5 2 8 6 9 4]
  [5 4 2 9 1 6 3 7 8]]]


3

Notice how storing sudoku_game and sudoku_solution in three dimensions makes more sense than adding the data from both to one 2D array.

### The fourth dimension
Printing arrays is a good way to check code output for small arrays like sudoku_game_and_solution, but it becomes unwieldy when dealing with bigger arrays and those with higher dimensions. Another important check is to look at the array's .shape.

Now, you'll create a 4D array that contains two sudoku games and their solutions

1.- Create another 3D array called new_game_and_solution with a different 2D game and 2D solution pair: new_sudoku_game and new_sudoku_solution. new_sudoku_game should appear before new_sudoku_solution.


2.- Create a 4D array called games_and_solutions by making an array out of the two 3D arrays: game_and_solution and new_game_and_solution, in that order.


3.- Print the shape of games_and_solutions.



In [17]:
#Create new_sudoku_game and new_sudoku_solution arrays
new_sudoku_game= np.array(([[0, 0, 4, 3, 0, 0, 0, 0, 0],
       [8, 9, 0, 2, 0, 0, 6, 7, 0],
       [7, 0, 0, 9, 0, 0, 0, 5, 0],
       [5, 0, 0, 0, 0, 8, 1, 4, 0],
       [0, 7, 0, 0, 3, 2, 0, 6, 0],
       [6, 0, 0, 0, 0, 1, 3, 0, 8],
       [0, 0, 1, 7, 5, 0, 9, 0, 0],
       [0, 0, 5, 0, 4, 0, 0, 1, 2],
       [9, 8, 0, 0, 0, 6, 0, 0, 5]]))

print(type(new_sudoku_game))

new_sudoku_solution=np.array(([[2, 5, 4, 3, 6, 7, 8, 9, 1],
       [8, 9, 3, 2, 1, 5, 6, 7, 4],
       [7, 1, 6, 9, 8, 4, 2, 5, 3],
       [5, 3, 2, 6, 9, 8, 1, 4, 7],
       [1, 7, 8, 4, 3, 2, 5, 6, 9],
       [6, 4, 9, 5, 7, 1, 3, 2, 8],
       [4, 2, 1, 7, 5, 3, 9, 8, 6],
       [3, 6, 5, 8, 4, 9, 7, 1, 2],
       [9, 8, 7, 1, 2, 6, 4, 3, 5]]))

print(type(new_sudoku_solution))

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>


In [18]:
# Create a second 3D array of another game and its solution 
new_game_and_solution = np.array([new_sudoku_game,new_sudoku_solution])
# Create a 4D array of both game and solution 3D arrays
games_and_solutions = np.array([game_and_solution,new_game_and_solution,])

# Print the shape of your 4D array
print(games_and_solutions.shape)
np.ndim(games_and_solutions)

(2, 2, 9, 9)


4

The .shape of (2, 2, 9, 9) means that there are two sets of game/solution pairs. Within each game/solution pair, all arrays have nine rows and nine columns. That's exactly right! If there were ten game/solution pairs, the .shape would be (10, 2, 9, 9).

#### Flattening and reshaping
You've learned to change not only array shape but also the number of dimensions that an array has. To test these skills, you'll change sudoku_game from a 2D array to a 1D array and back again. Can we trust NumPy to keep the array elements in the same order after being flattened and reshaped? Time to find out.

1.- Flatten sudoku_game so that it is a 1D array, and save it as flattened_game.


2.-Print the .shape of flattened_game.

In [23]:
sudoku_game=np.array([[0, 0, 4, 3, 0, 0, 2, 0, 9],
       [0, 0, 5, 0, 0, 9, 0, 0, 1],
       [0, 7, 0, 0, 6, 0, 0, 4, 3],
       [0, 0, 6, 0, 0, 2, 0, 8, 7],
       [1, 9, 0, 0, 0, 7, 4, 0, 0],
       [0, 5, 0, 0, 8, 3, 0, 0, 0],
       [6, 0, 0, 0, 0, 0, 1, 0, 5],
       [0, 0, 3, 5, 0, 8, 6, 9, 0],
       [0, 4, 2, 9, 1, 0, 3, 0, 0]])
print(sudoku_game.shape)

(9, 9)


In [20]:
# Flatten sudoku_game
flattened_game = sudoku_game.flatten()

# Print the shape of flattened_game
print(flattened_game.shape)

(81,)


3.-Reshape the flattened_game back to its original shape of nine rows and nine columns; save the new array as reshaped_game.

In [24]:
# Reshape flattened_game back to a nine by nine array
reshaped_game = flattened_game.reshape((9, 9))

# Print sudoku_game and reshaped_game
print(sudoku_game.shape)
print(reshaped_game.shape)
print(reshaped_game)

(9, 9)
(9, 9)
[[0 0 4 3 0 0 2 0 9]
 [0 0 5 0 0 9 0 0 1]
 [0 7 0 0 6 0 0 4 3]
 [0 0 6 0 0 2 0 8 7]
 [1 9 0 0 0 7 4 0 0]
 [0 5 0 0 8 3 0 0 0]
 [6 0 0 0 0 0 1 0 5]
 [0 0 3 5 0 8 6 9 0]
 [0 4 2 9 1 0 3 0 0]]


Phew! Nice work resurrecting that sudoku game. Notice that .flatten() preserves the order of array elements—when the array is reshaped back to its original shape, the numbers are in the exact same places as they were before flattening.